name: Unit Tests (dev)

on:
  push:
    branches: [develop]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle to dev
        run: databricks bundle deploy -t dev

      - name: Run unit tests
        run: databricks bundle run tfnsw_test_suite -t dev